
<div class="footer">
       
        
    <div class="copyright">

        
        <span>&copy;</span>
        <script type="text/javascript">var year = new Date();document.write(year.getFullYear());</script>
        <span> - </span>

        

        <a href="https://www.linkedin.com/in/davide-fontana-186a68272/" style="color: #fff;" target="_blank">
            <i class="fa-brands fa-linkedin"></i></a>

        <a href="mailto:davidefon98@gmail.com" style="color: #fff;">
            <i class="fa-sharp fa-regular fa-envelope"></i></a>
        
    </div>
    
</div>

